socialproject/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name="accounts"

urlpatterns=[
    path('login/',auth_views.LoginView.as_view(template_name='login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('signup/',views.signup.as_view(),name='signup'),
    path('flame/',views.Flame,name='flame'),
]

socialproject/posts/urls.py
from django.urls import path
from . import views

app_name='posts'

urlpatterns=[
    path('',views.PostList.as_view(),name='all'),
    path('new/',views.CreatePost.as_view(),name='create'),
    path('by/<username>',views.UserPosts.as_view(),name='for_user'),
    path('by/<username>/<pk>',views.PostDetail.as_view(),name='single'),
    path('delete/<pk>',views.DeletePost.as_view(),name='delete'),
]

socialproject/socialproject/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='home'),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('test/',views.TestPage.as_view(),name='test'),
    path('thanks/',views.ThanksPage.as_view(),name='thanks'),
    path('posts/',include('posts.urls',namespace='posts')),
    path('groups/',include('groups.urls',namespace='groups')),
    
]

socialproject/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <meta charset="utf-8">
        <title>Social site</title>
         <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap-theme.min.css" integrity="sha384-6pzBo3FDv/PJ8r2KRkGHifhEocL+1X2rVCTTkUfGk7/0pbek5mMa1upzvWbrUbOZ" crossorigin="anonymous">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<!-- Latest compiled and minified JavaScript -->
<script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>

        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
        

        <link rel="stylesheet" href="{% static 'css/master.css' %}">
        <style>
            body{
                background-color: #2f294f;
            }
            #note{
                position: absolute;
  color: rgba(249,241,204,1);
  left: 0;
  right: 0;
  bottom: 20px;
  margin: auto;
  text-align: center;
  user-select: none;
  font-family: Arial;
            }
        </style>
    </head>
    <body>
        
        <nav class="navbar mynav" role="navigation" id="navbar">
            <div class="container">
                <a class="navbar-brand mynav" href="{% url 'home' %}">Star Social</a>
             <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'posts:create' %}">Post</a></li>
                    <li><a href="{% url 'groups:all' %}">Groups</a></li>
                    <li><a href="{% url 'groups:create' %}">Create Group</a></li>
                    <li><a href="{% url 'accounts:flame' %}">FLAMES</a></li>
                    
                    <li class="dropdown"><a class="nav-link" href="#" data-toggle="dropdown"><img src="{% static 'images/gokuUI.png' %}" style="width:50px;">
                      </a> 
                      <ul class="dropdown-menu">
                        
                        <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                        
                      </ul>
                    </li>
                    
                    {% else %}
                    <li><a href="{% url 'groups:all' %}">Groups</a></li>
                    <li><a href="{% url 'accounts:login' %}">Login</a></li>
                    <li><a href="{% url 'accounts:signup' %}">Sign Up</a></li>
                    {% endif %}
                </ul>
           </div>
        </nav>
        
    <div class="container content">
        {% block content %}
        {% endblock %}
        </div>
        
                
    </body>
    <canvas id="canvas"></canvas>
    <span id="note">Click to add fireflies</span>
    <script type="text/javascript" src="{% static 'js/master.js' %}"></script>
</html>

socialproject/templates/flames.html
{% extends "base.html" %}
{% load static %}
        {% block content %}
        <style>
            input{
                color:red;
            }
        </style>
        <div class="container">
            <form method="post"> 
                {{form.as_p}}
                {% csrf_token %}
                <input type="submit" class="btn btn-primary" value="Submit">
                </form>
                
        </div>
        <h1><h1 style="color: coral;">{{cont}}</h1><h1 style="color: crimson;">{{yourname}}</h1><h1 style="color: coral;">{{cont1}}</h1><h1 style="color: crimson;">{{yourcrushname}}</h1><h1 style="color: coral;">{{cont3}}</h1><h1 style="color: crimson;">{{output}}</h1></h1>
        
        {% endblock %}

socialproject/templates/index.html
{% extends "base.html" %}
{% block content %}
<h1>Social Media Project</h1>
{% endblock %}

socialproject/templates/test.html
{% extends "base.html" %}
{% block content %}
<h1>You are now logged in</h1>
{% endblock %}

socialproject/templates/thanks.html
{% extends "base.html" %}
{% block content %}
<h1>You are logged out ,come back soon</h1>
{% endblock %}